version: "3.2"
networks:
  default:
    driver: bridge

services:
  nodejs_ui:
    image: node:18.1.0
    working_dir: /home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/:/home/node/app
    ports:
      - 3001:3000
    command: bash -c "npm i && npm run start-dev"
#    networks:
#      - partyhub
  mongo:
    image: mongo:4.4.13
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
    ports:
      - 27017:27017
#    networks:
#      - partyhub
  mongo-express:
    image: mongo-express:0.54.0
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    ports:
      - 8081:8081
    depends_on:
      - mongo
#    networks:
#      - partyhub
